apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  initContainers:
    - name: log-shipper
      image: busybox
      restartPolicy: Always
      command: ["sh", "-c", "while true; do echo 사이드카가 로그 수집 중; sleep 10; done"]
  containers:
    - name: main-app
      image: nginx
