apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "special"
      effect: "NoSchedule"
  containers:
    - name: web
      image: nginx
