apiVersion: v1
kind: LimitRange
metadata:
  name: day9-limitrange
  namespace: day9-ns
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 32Mi
      max:
        cpu: 300m
        memory: 192Mi
