apiVersion: v1
kind: ResourceQuota
metadata:
  name: day9-quota
  namespace: day9-ns
spec:
  hard:
    pods: "2"
    requests.cpu: "300m"
    requests.memory: 192Mi
    limits.cpu: "600m"
    limits.memory: 384Mi
