apiVersion: v1
kind: Pod
metadata:
  name: secctx-group-pod
  namespace: day9-ns
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: box
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        readOnlyRootFilesystem: true
