apiVersion: v1
kind: Pod
metadata:
  name: secctx-conflict-pod
  namespace: day9-ns
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 0
  containers:
    - name: box
      image: busybox
      command: ["sleep", "3600"]
