events {}

http {
    upstream backend_pool {
        server backend-a:80;
        server backend-b:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_pool;
        }
    }
}
